# Camera intrinsics  
  fx: 1076.873461155599
  fy: 1075.6597751410989
  cx: 992.9846880476084
  cy: 523.3036649549291
  k1: -0.288031175827382
  k2: 0.06307797572758711
  p1: -0.00009558234169386542
  p2: 0.0014252659205132162

# Calibration target parameters
  marker_size: 0.19 # ArUco marker size (our test data uses 0.16m; adjust to match your marker size)
  delta_width_qr_center: 0.55 # Half the distance between the centers of two markers in the horizontal direction 
  delta_height_qr_center: 0.35 # Half the distance between the centers of two markers in the vertical direction
  delta_width_circles: 0.5 # Distance between the centers of two circles in the horizontal direction
  delta_height_circles: 0.4 # Distance between the centers of two circles in the vertical direction
  circle_radius: 0.12 # Radius of the circle 

# Distance filter 22 bag
  x_min: 0.8 # avia and mid360: 2.0 ouster: 1.5
  x_max: 1.2
  y_min: -0.5 # right side
  y_max: 0.7 # left side
  z_min: -0.5 # avia and mid360: -0.5 ouster: -0.8
  z_max: 0.4
  bag_path: "$(find fast_calib)/calib_data/22.bag"
  image_path: "$(find fast_calib)/calib_data/22.png"

# Distance filter 33 bag
  #x_min: 0.8 # avia and mid360: 2.0 ouster: 1.5
  #x_max: 1.3
  #y_min: -0.3 # right side
  #y_max: 0.8 # left side
  #z_min: -0.5 # avia and mid360: -0.5 ouster: -0.8
  #z_max: 0.4
  #bag_path: "$(find fast_calib)/calib_data/33.bag"
  #image_path: "$(find fast_calib)/calib_data/33.png"

# Distance filter 44 bag
  #x_min: 1.0 # avia and mid360: 2.0 ouster: 1.5
  #x_max: 1.8
  #y_min: -0.65 # right side
  #y_max: 0.45 # left side
  #z_min: -0.4 # avia and mid360: -0.5 ouster: -0.8
  #z_max: 0.35
  #bag_path: "$(find fast_calib)/calib_data/44.bag"
  #image_path: "$(find fast_calib)/calib_data/44.png"

# Input
  lidar_topic: "/ouster/points" # /ouster/points /livox/lidar

# Output
  output_path: "$(find fast_calib)/output"